PySide : Don't specify MACOSX_DEPLOYMENT_TARGET
This was leading to the following build error :

```
error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.9" but "10.12" during configure
```

I suspect this is due to the recent Python upgrade, since PySide seems to use distutils, and that has many references to MACOSX_DEPLOYMENT_TARGET.