OIIO : Disable FFMPEG plugin.
We haven't been building this on OS X because the build machine didn't have it. On Linux I believe we also haven't built it to date, but we don't currently have access to the traditional build machine. My new build machine has an incompatible version of FFMPEG installed, hence the need to disable. For the record, here is the build error :

```
In file included from /usr/local/include/libavutil/avutil.h:288,
                 from /usr/local/include/libavutil/samplefmt.h:24,
                 from /usr/local/include/libavcodec/avcodec.h:31,
                 from /usr/local/include/libavformat/avformat.h:306,
                 from /home/john/dev/gafferDependencies/oiio-Release-1.5.17/src/ffmpeg.imageio/ffmpeginput.cpp:33:
/usr/local/include/libavutil/common.h:30:2: error: #error missing -D__STDC_CONSTANT_MACROS / #define __STDC_CONSTANT_MACROS
In file included from /usr/local/include/libavutil/avutil.h:288,
                 from /usr/local/include/libavutil/samplefmt.h:24,
                 from /usr/local/include/libavcodec/avcodec.h:31,
                 from /usr/local/include/libavformat/avformat.h:306,
                 from /home/john/dev/gafferDependencies/oiio-Release-1.5.17/src/ffmpeg.imageio/ffmpeginput.cpp:33:
/usr/local/include/libavutil/common.h: In function ‘int32_t av_clipl_int32_c(int64_t)’:
/usr/local/include/libavutil/common.h:191: error: ‘UINT64_C’ was not declared in this scope
/home/john/dev/gafferDependencies/oiio-Release-1.5.17/src/ffmpeg.imageio/ffmpeginput.cpp: In member function ‘virtual bool OpenImageIO::v1_5::FFmpegInput::open(const std::string&, OpenImageIO::v1_5::ImageSpec&)’:
/home/john/dev/gafferDependencies/oiio-Release-1.5.17/src/ffmpeg.imageio/ffmpeginput.cpp:240: error: ‘PIX_FMT_RGB24’ was not declared in this scope
/home/john/dev/gafferDependencies/oiio-Release-1.5.17/src/ffmpeg.imageio/ffmpeginput.cpp: In member function ‘void OpenImageIO::v1_5::FFmpegInput::read_frame(int)’:
/home/john/dev/gafferDependencies/oiio-Release-1.5.17/src/ffmpeg.imageio/ffmpeginput.cpp:365: error: ‘PIX_FMT_RGB24’ was not declared in this scope
make[2]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ffmpeg.imageio/ffmpeginput.cpp.o] Error 1
make[1]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/all] Error 2

```

If we want to use the FFMPEG plugin in the future, we should consider including a known version of FFMPEG itself in gafferDependencies, so that we know what we're getting. I suspect we'd also need to update the ImageReader and ImageWriter to better support movie files anyway.