USD : Patch internal Boost::Python to fix Cortex build with Xcode 15
We require this patch to build Cortex as IEUSDModule.cpp includes both boost/python.hpp and pxr/external/boost/python.hpp which causes clang to complain about redefinition of `dealloc()`.

Even though `dealloc()` is in two different namespaces, the `extern "C"` causes clang to consider this a redefinition as C doesn't have namespaces...

```
In file included from contrib/IECoreUSD/src/IECoreUSD/bindings/IEUSDModule.cpp:46:
In file included from include/boost/python.hpp:48:
In file included from include/boost/python/opaque_pointer_converter.hpp:15:
include/boost/python/detail/dealloc.hpp:11:21: error: redefinition of 'dealloc'
        inline void dealloc(PyObject* self)
include/pxr/external/boost/python/detail/dealloc.hpp:20:21: note: previous definition is here
        inline void dealloc(PyObject* self)
```